<a href="https://colab.research.google.com/github/sindhushaThangaraj/sample/blob/main/NumPy_Tutorial_(1)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Load in NumPy (remember to pip install numpy first)

In [ ]:
import numpy as np

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [ ]:
### The Basics

In [ ]:
a = np.array([1,2,3], dtype='int64')
print(a)
print(a.dtype)

[1 2 3]
int64


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b.ndim

[[9. 8. 7.]
 [6. 5. 4.]
 [9. 8. 7.]
 [6. 5. 4.]]


2

In [ ]:
# Get Dimension
b.ndim

2

In [ ]:
# Get Shape
a.shape

(3,)

In [ ]:
# Get Type
b.dtype

dtype('float64')

In [ ]:
# Get Size
a.itemsize


8

In [ ]:
# Get total size
a.nbytes


24

In [ ]:
# Get number of elements
b.size

12

In [ ]:
### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.ndim

2

In [ ]:
# Get a specific element [r, c]
a[0,0]

np.int64(1)

In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, -1:-6:-2]

array([7, 5, 3])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [ ]:
# Get specific element (work outside in)
b[1,1,1]

np.int64(8)

In [ ]:
# replace
b[:,0,:] = [[9,9],[8,8]]

In [ ]:
b

array([[[9, 9],
        [9, 9]],

       [[8, 8],
        [8, 8]]])

In [ ]:
### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
c=np.ones((4,2,2,2), dtype='int32')
c.ndim

4

In [ ]:
# Any other number
np.full((2,3), 999)

array([[999, 999, 999],
       [999, 999, 999]])

In [ ]:
# Any other number (full_like)
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.87452267, 0.88478986],
       [0.65482101, 0.31088615],
       [0.87899141, 0.79344477],
       [0.6353367 , 0.18755031]])

In [ ]:
# Random Integer values
np.random.randint(0,6, size=(4,3))

array([[2, 3, 5],
       [0, 3, 1],
       [1, 1, 5],
       [4, 5, 1]])

In [ ]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [ ]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

In [ ]:
##### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
#b = a
b[0] = 100
print(a)

In [ ]:
### Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
# Take the sin
np.cos(a)



In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [ ]:
##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [ ]:
##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=1)

In [ ]:
np.sum(stats, axis=0)

In [ ]:
### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

In [ ]:
import numpy as np

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

# Reshape into (2, 3)
after = before.reshape((2, 2, 2))  # Corrected to match the total number of elements
print(after)


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

In [ ]:
### Miscellaneous
##### Load Data from File

In [55]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

FileNotFoundError: data.txt not found.

In [ ]:
##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))